# Generated by Django 3.2.12 on 2022-08-06 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_image_blog_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='img',
            new_name='image',
        ),
    ]
