# Generated by Django 3.2.12 on 2022-08-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='creation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
