# Generated by Django 3.2.12 on 2022-08-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_image_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='img',
        ),
        migrations.RemoveField(
            model_name='page',
            name='img_post_date',
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='blogs.image'),
        ),
    ]
