# Generated by Django 3.2.12 on 2022-08-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10, null=True)),
                ('creation', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
